Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
      v.name = "elasteicsearch-tester"
  end
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "myprecise.box"
  config.vm.network :private_network, ip: "192.168.0.50"

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--cpus", "2",
      "--memory", "3548",
    ]
  end

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "main.yml"
   end

end
