version: '2'
services:
  elasticactive:
    build: elasticsearch/
    ports:
      - "9200:9200"
    networks:
      - elk
    volumes:
      - activepersistency:/usr/share/elasticsearch/data
  visualization:
    build: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticactive
  test-registry:
    build: registry/
    ports:
      - "3000:3000"
    depends_on:
      - elasticactive


volumes:
  activepersistency:
    driver: local

networks:
  elk:
    driver: bridge
