Vagrant.configure("2") do |config|
  config.vm.define :alpha do |active|
    active.vm.box = "ubuntu/trusty64"
    active.vm.network :private_network, ip: "10.0.0.10"
    active.vm.hostname = "active-compute"
    active.vm.provider :virtualbox do |vb|
      vb.name = "active-computer"
      vb.customize [
        "modifyvm", :id,
        "--cpus", "2",
        "--memory", "5048",
      ]
    end
    active.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbook/active.yml"
     end


  end

  config.vm.define :beta do |registry|
    registry.vm.box = "ubuntu/trusty64"
    registry.vm.hostname = "myprecise.box"
    registry.vm.network :private_network, ip: "10.0.0.11"
    registry.vm.hostname = "registry"
  end


end
